[project]
name = "ai-news-direct"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "curl-cffi>=0.12.0",
    "python-dateutil>=2.9.0.post0",
]
